### ISSUE TITLE
Help to port Socket.IO to Emscripten (WebAssembly)

### ISSUE THREAD

**Issue by skhaz** [socketio/socket.io-protocol#35] opened 2024-12-04 16:33 UTC
I am creating a Socket.IO implementation for Emscripten in C++, purely using WebSockets.

I followed the documentation for several days and even tried reverse-engineering the client for web browsers, but without success.

Below is a step-by-step description of what I am doing, and I would be very grateful to know what I did wrong to experience frequent disconnections.

**WebSocket URL** `ws://localhost:3000/socket.io/?transport=websocket&EIO=4` (no HTTP!)

I connect and I receive

```
0{"sid":"w4NlzSj3BPm24GGDAAAX","upgrades":[],"pingInterval":25000,"pingTimeout":20000,"maxPayload":1000000}
```

Then I anwser with

```
0
```

Then the connection keeps for while...

If I try to send

```
42["messsage","hello world"]
```

I got disconnected immediately.

Also, if I receive 

```
2
```

And anwser with

```
3
```

I got disconnected immediately too.

**Comment by darrachequesne** [comment] 2024-12-05 10:30
Duplicate of https://github.com/socketio/socket.io/discussions/5251.

**Closed as completed by darrachequesne** 2024-12-05 10:30 UTC
